.TH vo 1 "Mar 30, 2023" "OpenMandriva" "Developer Tools"
.SH NAME
vo \- simple RPM spec file generator for packages for GNU Octave
.SH SYNOPSIS
.br
.B vo
[-b|--binary]
<app>
.SH OPTIONS
TP.
.BI \-b\fR,\ \fB\-\-binary
Create an octave package depending on arch
.SH DESCRIPTION
\fBvo\fR is a simple generator for RPM spec files (the
files controlling the build process of RPM packages) packaging octave packages.
.PP
\fBvo\fR creates a spec file template, and invokes an editor (usually
\fBvim\fR, but \fBvo\fR respects the \fBEDITOR\fR and \fBVISUAL\fR environment
variables) to edit the file.
.PP
All you need to do is fill in the blanks and possibly overwrite some default
settings.
.PP
If you are trying to package something not related to Octave, \fBvs (1)\fR and
\fBvl\fR are preferrable over \fBvo\fR.
.SH EXAMPLE
.SP
.NF
  $ vo somepackage
.br
  $ cd ~/abf/octave-somepackage
.br
  $ abb build
.FI
.PD
.SH "SEE ALSO"
.BR rpm (8),
.BR vs (1),
.BR vl (1),
.BR vj (1),
.BR vp (1),
.BR vpl (1),
.BR e (1)

.SH AUTHOR
.nf
Bernhard Rosenkraenzer <bero@lindev.ch>
.nf
mandian <mandian@tutanota.com>
.fi
