.TH vpl 1 "Sep 1, 2026" "OpenMandriva" "Developer Tools"
.SH NAME
vpl \- simple RPM spec file generator for perl modules
.SH SYNOPSIS
.br
.B vpl
[-s|--snapshot]
<module>
.SH OPTIONS
.BI \-s\fR,\ \fB\-\-snapshot
Create constructs to allow building an SCM snapshot
.SH DESCRIPTION
\fBvpl\fR ("vi perl-specfile") is a simple generator for RPM spec files (the
files controlling the build process of RPM packages) packaging perl modules.
.PP
\fBvpl\fR looks the module up on MetaCPAN and fills in version, summary,
license, source URL, description and \fBBuildRequires\fR (\fBperl(...)\fR
from configure/build/runtime/test requirements) from CPAN metadata, then
invokes an editor (usually \fBvim\fR, but \fBvpl\fR respects the
\fBEDITOR\fR and \fBVISUAL\fR environment variables) to edit the file.
.PP
The module name may be given as \fIFoo-Bar\fR, \fIFoo::Bar\fR, or
\fIperl-Foo-Bar\fR.
.PP
All you need to do is review the generated fields and possibly overwrite
some default settings.
.PP
If you are trying to package a (non-perl) library, \fBvl (1)\fR is preferrable over
\fBvpl\fR. Use \fBvs (1)\fR for generic packages.
.SH EXAMPLE
.SP
.NF
  $ vpl somemodule
.br
  $ cd ~/abf/perl-somemodule
.br
  $ abb build
.FI
.PD
.SH "SEE ALSO"
.BR rpm (8),
.BR vs (1),
.BR vl (1),
.BR vgo (1),
.BR vj (1),
.BR vo (1),
.BR vp (1),
.BR e (1)

.SH AUTHOR
.nf
Bernhard Rosenkraenzer <bero@lindev.ch>
.fi
